from __future__ import annotations


JUDGE_PATHS = (
    "docs/START_HERE.md",
    "docs/SUBMISSION_PACKET.md",
    "docs/FLF_BEFORE_AFTER_COMPARISON.md",
    "docs/FLF_SELF_ASSESSMENT_AND_LIMITATIONS.md",
    "docs/HUMAN_AUDIT_GUIDE.md",
    "docs/NEW_SOURCE_UPDATE_DEMO.md",
    "docs/FLF_SUBMISSION_DRAFT.md",
    "docs/ARCHITECTURE.md",
    "docs/OPERATIONAL_WORKFLOW_AND_REALISM.md",
    "docs/SUBMISSION_ARTIFACT_SUMMARY.md",
    "ui/index.html",
    "docs/review/REVIEWER_START_HERE.md",
    "docs/review/TIER1_HUMAN_REVIEW_CHECKLIST.csv",
    "docs/review/LHC_HUMAN_AUDIT_PACKET.md",
    "docs/review/EGGS_HUMAN_AUDIT_PACKET.md",
    "docs/review/COVID_HUMAN_AUDIT_PACKET.md",
    "docs/review/LHC_HUMAN_AUDIT_CHECKLIST.csv",
    "docs/review/EGGS_HUMAN_AUDIT_CHECKLIST.csv",
    "docs/review/COVID_HUMAN_AUDIT_CHECKLIST.csv",
    "docs/review/BLINDED_BASELINE_AUDIT.md",
    "docs/review/MULTI_MODEL_BLINDED_BASELINE_AUDIT.md",
    "examples/covid_origins_slice/BEST_REGIONS.md",
    "examples/covid_origins_slice/worked_region_bayesian_disagreement_map.md",
    "examples/covid_origins_slice/flat_synthesis_baseline.md",
    "examples/covid_origins_slice/decision_space_erosion_audit.md",
    "examples/lhc_black_holes/full_case_index.md",
    "examples/lhc_black_holes/full_case_map.md",
    "examples/lhc_black_holes/full_case_flat_synthesis_baseline.md",
    "examples/lhc_black_holes/BEST_REGIONS.md",
    "examples/lhc_black_holes/worked_region_cosmic_ray_map.md",
    "examples/lhc_black_holes/flat_synthesis_baseline.md",
    "examples/lhc_black_holes/decision_space_erosion_audit.md",
    "examples/lhc_black_holes/worked_region_public_risk_framing_map.md",
    "examples/lhc_black_holes/investigator_task_queue.md",
    "examples/eggs/full_case_index.md",
    "examples/eggs/full_case_map.md",
    "examples/eggs/full_case_flat_synthesis_baseline.md",
    "examples/eggs/BEST_REGIONS.md",
    "examples/eggs/worked_region_observational_vs_rct_map.md",
    "examples/eggs/flat_synthesis_baseline.md",
    "examples/eggs/decision_space_erosion_audit.md",
    "examples/eggs/investigator_task_queue.md",
)
