from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

from epistemic_case_mapper.io import read_yaml
from epistemic_case_mapper.schema import CaseManifest
from epistemic_case_mapper.submission_manifest import SubmissionManifest, load_submission_manifest
from epistemic_case_mapper.unseen_quality import (
    init_quality_test,
    quality_signals,
    quality_summary,
    validate_quality_test,
    write_quality_risk_tasks,
)


ENGINE_ROOT = Path(__file__).resolve().parents[2]


def _run_many(repo_root: Path, commands: list[list[str]], package: str) -> int:
    for command in commands:
        result = _run(repo_root, command, package)
        if result != 0:
            return result
    return 0


def _run(repo_root: Path, command: list[str], package: str) -> int:
    target_script = repo_root / command[0]
    engine_script = ENGINE_ROOT / command[0]
    script_path = target_script if target_script.is_file() else engine_script
    if not script_path.is_file():
        print(
            "package_command_unavailable "
            f"missing_target_script={target_script} "
            f"missing_engine_script={engine_script} "
            "This command requires an Epistemic Case Mapper repository checkout "
            "either at --repo-root or as the installed engine source.",
            file=sys.stderr,
        )
        return 2

    existing_pythonpath = os.environ.get("PYTHONPATH")
    python_paths = [str(repo_root / "src")]
    engine_src = ENGINE_ROOT / "src"
    if engine_src != repo_root / "src":
        python_paths.append(str(engine_src))
    if existing_pythonpath:
        python_paths.append(existing_pythonpath)
    env = {**os.environ, "PYTHONPATH": os.pathsep.join(python_paths)}
    result = subprocess.run(
        [
            sys.executable,
            str(script_path),
            *command[1:],
            "--repo-root",
            str(repo_root),
            "--manifest",
            package,
        ],
        cwd=repo_root,
        env=env,
        text=True,
        check=False,
    )
    return result.returncode


def _prepare_package(repo_root: Path, package: str) -> int:
    result = _run_many(
        repo_root,
        [
            ["scripts/build_ui_data.py"],
            ["scripts/build_tier1_review_checklist.py"],
        ],
        package,
    )
    if result != 0:
        return result
    _copy_ui_shell(repo_root)
    manifest = load_submission_manifest(repo_root, package)
    _write_reviewer_start(repo_root, manifest)
    print("Prepared package assets")
    return 0
def _copy_ui_shell(repo_root: Path) -> None:
    target_dir = repo_root / "ui"
    target_dir.mkdir(parents=True, exist_ok=True)
    for name in ("index.html", "styles.css", "app.js"):
        shutil.copyfile(ENGINE_ROOT / "ui" / name, target_dir / name)
def _write_reviewer_start(repo_root: Path, manifest: SubmissionManifest) -> None:
    output_path = repo_root / "docs/review/REVIEWER_START_HERE.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {manifest.package_label} Reviewer Start",
        "",
        "Status: `generated`",
        "",
        "Use this page to orient to the package artifacts generated by the Epistemic Case Mapper engine.",
        "",
        "## Fast Path",
        "",
    ]
    if manifest.ui_hero.links:
        for link in manifest.ui_hero.links:
            lines.append(f"- {link.label}: `{link.path}`")
    else:
        for path in manifest.judge_paths:
            lines.append(f"- `{path}`")
    lines.extend(["", "## Cases", ""])
    for case in manifest.cases:
        case_manifest = CaseManifest.model_validate(read_yaml(repo_root / case.case_path))
        lines.append(f"### {case.label}")
        lines.append("")
        lines.append(f"- Question: {case_manifest.question}")
        lines.append(f"- Case manifest: `{case.case_path}`")
        for region in case.worked_regions:
            lines.append(f"- Worked region `{region.region_id}`: `{region.map_path}`")
            lines.append(f"- Erosion audit `{region.region_id}`: `{region.audit_path}`")
        if case.task_queue is not None:
            lines.append(f"- Task queue: `{case.task_queue.path}`")
        quality = quality_summary(repo_root, case.case_key)
        if quality["paths"]["scorecard"]:
            lines.append(f"- Quality scorecard: `{quality['paths']['scorecard']}`")
        if quality["paths"]["riskTasks"]:
            lines.append(f"- Generated quality tasks: `{quality['paths']['riskTasks']}`")
        signals = quality_signals(repo_root, case.case_key, case_manifest)
        if signals:
            lines.append("")
            lines.append("Quality warnings:")
            for signal in signals[:8]:
                lines.append(f"- {signal.severity}: {signal.label} - {signal.evidence}")
        lines.append("")
    lines.extend(
        [
            "## Generated Assets",
            "",
            "- Static UI: `ui/index.html`",
            "- UI data: `ui/data.json`",
            "- Tier 1 checklist: `docs/review/TIER1_HUMAN_REVIEW_CHECKLIST.csv`",
            "",
        ]
    )
    output_path.write_text("\n".join(lines), encoding="utf-8")
def _init_quality(repo_root: Path, case_slug: str, title: str, question: str, force: bool) -> int:
    try:
        written = init_quality_test(repo_root, case_slug, title, question, force=force)
    except ValueError as exc:
        print(f"quality_init_failed {exc}", file=sys.stderr)
        return 1
    for path in written:
        print(f"Wrote {path.relative_to(repo_root).as_posix()}")
    if not written:
        print("No quality files changed")
    return 0
def _check_quality(repo_root: Path, case_slug: str) -> int:
    try:
        failures = validate_quality_test(repo_root, case_slug)
    except ValueError as exc:
        print(f"quality_check_failed {exc}", file=sys.stderr)
        return 1
    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        return 1
    print(f"Validated unseen-case quality review case={case_slug}")
    return 0
def _write_quality_tasks(repo_root: Path, manifest: SubmissionManifest, case_slug: str) -> int:
    try:
        case = manifest.case_for_key(case_slug)
    except KeyError:
        if len(manifest.cases) != 1:
            print(f"quality_task_failed unknown_case={case_slug}", file=sys.stderr)
            return 1
        case = manifest.cases[0]
    case_manifest = CaseManifest.model_validate(read_yaml(repo_root / case.case_path))
    path = write_quality_risk_tasks(repo_root, case_slug, case_manifest)
    print(f"Wrote {path.relative_to(repo_root).as_posix()}")
    return 0
